name: 'Bump Version'
on:
  pull_request:
    types: [opened, synchronize, reopened] # TODO: Only opened!
    branches:
      - main

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: write

jobs:
  bump-version:
    name: 'Bump Version on master'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: 'cat package.json'
        run: cat ./package.json

      - name: 'Automated Version Bump'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        with:
          tag-prefix: 'v'

      - name: 'cat package.json'
        run: cat ./package.json
